# Generated by Django 4.2.4 on 2023-08-10 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sensor',
            old_name='describe',
            new_name='description',
        ),
    ]
