# Generated by Django 4.2.3 on 2023-07-23 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='price')),
                ('image', models.URLField(max_length=100, verbose_name='image')),
                ('release_date', models.DateField(verbose_name='release_date')),
                ('lte_exists', models.BooleanField(default=False, verbose_name='lte_exists')),
                ('slug', models.SlugField()),
            ],
        ),
    ]
